### ISSUE TITLE
Consider adding NuGet support

### ISSUE THREAD

**Issue by Iter123** [rhynodegreat/CSharpGameLibrary#1]
It would be great if you could upload the project to nuget, would be much more convenient to add the library to my projects in VS- thanks!

**Comment by vazgriz** [comment]
I am planning to make this a Nuget package. However, I need to finish the bindings first and I need to figure out the right way to include the native dependency `glfw3` for Windows and, hopefully, Linux.

**Comment by vazgriz** [comment]
CSGL 0.1.0-alpha is now on NuGet. https://www.nuget.org/packages/CSharpGameLibrary/0.1.0-alpha
